package com.pettoyou.server.domains.pet.entity.enums;

public enum Species {
    /***
     * 고양이 종류
     */

    ABYSSINIAN("아비시니안"),
    AMERICAN_BOBTAIL("아메리칸 밥테일"),
    AMERICAN_CURL("아메리칸 컬"),
    AMERICAN_RINGTAIL("아메리칸 링테일"),
    AMERICAN_SHORTHAIR("아메리칸 쇼트헤어"),
    AMERICAN_WIREHAIR("아메리칸 와이어헤어"),
    ANATOLI("아나톨리"),
    CYPRUS("키프로스"),
    CYPRUS_APHRODITE("키프로스 아프로디테"),
    ARABIAN_MAU("아라비안 마우"),
    ASIAN("아시안"),
    TIFFANY("티파니"),
    AUSTRALIAN_MIST("오스트레일리안 미스트"),
    AUSTRALIAN_TIFFANY("오스트레일리안 티파니"),
    BAHRAIN_DILMUN("바레인 딜문"),
    BALINESE("발리니즈"),
    BAMBINO("밤비노"),
    BENGAL("벵갈"),
    BIRMAN("버먼"),
    BOMBAY("봄베이"),
    BRAMBLE("브램블"),
    BRAZILIAN_SHORTHAIR("브라질리안 쇼트헤어"),
    BRITISH_LONGHAIR("브리티시 롱헤어"),
    BRITISH_SHORTHAIR("브리티시 쇼트헤어"),
    BURMESE("버미즈"),
    BURMILLA("버밀라"),
    CALIFORNIA_SPANGLED("캘리포니아 스팽글드"),
    CEYLON("세일론"),
    CHANTILLY_TIFFANY("샹틸리 티파니"),
    CHARTREUX("샤르트뢰"),
    CHAUSIE("쵸시"),
    PERSIAN_CHINCHILLA("페르시안 친칠라"),
    CHITO("치토"),
    COLORPOINT_SHORTHAIR("컬러포인트 쇼트헤어"),
    CORNISH_REX("코니시 렉스"),
    CYMRIC("킴릭"),
    DEVON_REX("데본 렉스"),
    DUTCH_REX("더치 렉스"),
    DONSKOY("돈스코이"),
    DRAGON_LI("드래곤 리"),
    ELF("엘프"),
    DWELF("드웰프"),
    EGYPTIAN_MAU("이집션 마우"),
    EUROPEAN_SHORTHAIR("유러피안 쇼트헤어"),
    EXOTIC_SHORTHAIR("이그저틱 쇼트헤어"),
    EXOTIC_LONGHAIR("이그저틱 롱헤어"),
    FOLDEX("폴덱스"),
    FOREIGN_WHITE("포린 화이트"),
    GENETTA("제네타"),
    GERMAN_REX("저먼 렉스"),
    HAVANA_BROWN("하바나 브라운"),
    HIGHLANDER("하일랜더"),
    HIMALAYAN("히말라얀"),
    JAG("재그"),
    JAPANESE_BOBTAIL("재패니즈 밥테일"),
    JAVANESE("자바니즈"),
    JUNGLE_BOB("정글밥"),
    KANANI("카나니"),
    KARELIAN_BOBTAIL("카렐리안 밥테일"),
    KASHMIR("카슈미르"),
    KHAO_MANEE("카오 마니"),
    KINKALOW("킨카로우"),
    KOHANA("코호나"),
    KORAT("코랏"),
    KORN_JA("콘 자"),
    KURILIAN_BOBTAIL("쿠릴리안 밥테일"),
    LAMBKIN("램킨"),
    LAPERM("라펌"),
    LYCYOI("라이코이"),
    MAINE_COON("메인쿤"),
    MALAYSIAN("말레이시아"),
    MANDALAY("만달레이"),
    MANX("맹크스"),
    MEKONG_BOBTAIL("메콩 밥테일"),
    MINSKIN("민스킨"),
    MINUET("미뉴에트"),
    MOJAVI_BOB("모하비밥"),
    MOJAVI_SPOTTED("모하비 점무늬"),
    MUNCHKIN("먼치킨"),
    NEBELUNG("네벨룽"),
    NEPALAYAN("네팔라얀"),
    NEVA_MASQUERADE("네바마스커레이드"),
    NEW_ZEALAND("뉴질랜드"),
    NORWEGIAN_FOREST("노르웨이 숲"),
    OCICAT("오시캣"),
    OJOS_AZULES("오호스 아즐레스"),
    OREGON_REX("오리건 렉스"),
    ORIENTAL_BICOLOR("오리엔탈 바이컬러"),
    ORIENTAL_LONGHAIR("오리엔탈 롱헤어"),
    ORIENTAL_SHORTHAIR("오리엔탈 쇼트헤어"),
    OWIHI_BOB("오위히 밥"),
    PERSIAN("페르시안"),
    TRADITIONAL_PERSIAN("트래디셔널 페르시안"),
    PANTHERETTE("팬서렛"),
    PETERBALD("피터볼드"),
    PIXIE_BOB("픽시 밥"),
    RAGAMUFFIN("라가머핀"),
    RAGDOLL("랙돌"),
    RAAS("라아스"),
    RUSSIAN_BLUE("러시안 블루"),
    RUSSIAN_WHITE("러시안 화이트"),
    RUSSIAN_BLACK("러시안 블랙"),
    RUSSIAN_TABBY("러시안 태비"),
    SAFARI("사파리"),
    SAM_SAWET("샘 사웨트"),
    SAVANNAH("사바나"),
    SCOTTISH_FOLD("스코티시 폴드"),
    SELKIRK_REX("셀커크 렉스"),
    SERENGETI("세렝게티"),
    SERRADE_PETITE("세라데 쁘띠"),
    SEYCHELLES("세이셸"),
    SIAMESE("샴"),
    SIBELLA("시벨라"),
    SIBERIAN("시베리안"),
    SINGAPURA("싱가푸라"),
    SKOOKUM("스쿠쿰"),
    SNOWSHOE("스노우슈"),
    SOKOKE("소코케"),
    SOMALI("소말리"),
    SPHYNX("스핑크스"),
    SUPHALAK("수팔락"),
    TENNESSEE_REX("테네시 렉스"),
    THAI("타이"),
    THAI_LILAC("타이 라일락"),
    THAI_BLUE_POINT("타이 블루 포인트"),
    THAI_LILAC_POINT("타이 라일락 포인트"),
    TIBETAN("티베탄"),
    TONKINESE("통키니즈"),
    TOYBOB("토이밥"),
    TOYGER("토이거"),
    TURKISH_ANGORA("터키시 앙고라"),
    TURKISH_VAN("터키시 반"),
    VAN("반"),
    UKRAINIAN_LEVKOY("유크레이니언 레브코이"),
    URAL_REX("우랄 렉스"),
    USSURI("우수리"),
    YORK_CHOCOLATE("요크 초콜릿"),

    /***
     * 강아지 종류
     */

    GORDON_SETTER("고든 세터"),
    COTON_DE_TULEAR("꼬똥 드 툴레아"),
    GOLDENDOODLE("골든두들"),
    GOLDEN_RETRIEVER("골든 리트리버"),
    GREAT_DANE("그레이트 데인"),
    GREAT_SWISS_MOUNTAIN_DOG("그레이트 스위스 마운틴 독"),
    GREAT_PYRENEES("그레이트 피레니즈"),
    GREYHOUND("그레이 하운드"),
    GREENLAND_DOG("그린란드견"),
    GLEN_OF_IMAAL_TERRIER("글렌 오브 이말 테리어"),
    KISHU("기슈견"),
    NEAPOLITAN_MASTIFF("나폴리탄 마스티프"),
    NORWEGIAN_BUHUND("노위지언 부훈트"),
    NORWEGIAN_ELKHOUND("노르웨이 엘크 하운드"),
    NORWICH_TERRIER("노리치 테리어"),
    NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER("노바스코샤 덕 톨링 레트리버"),
    NORFOLK_TERRIER("노퍽 테리어"),
    NEWFOUNDLAND("뉴펀들랜드"),
    DACHSHUND("닥스훈트"),
    DALMATIAN("달마시안"),
    DANDIE_DINMONT_TERRIER("댄디 딘몬트 테리어"),
    DOGO_CANARIO("도고 까나리오"),
    DOGO_ARGENTINO("도고 아르헨티노"),
    DOBERMAN_PINSCHER("도베르만 핀셔"),
    DOSA("도사견"),
    DONGGYEONGI("동경이"),
    LAGOTTO_ROMAGNOLO("라고토 로마뇰로"),
    LHASA_APSO("라사압소"),
    RAFEIRO_DO_ALENTEJO("라페이로 도 알렌테조"),
    LAPPONIAN_HERDER("라포니안 허더"),
    LABRADOR_RETRIEVER("래브라도 리트리버"),
    REDBONE_COONHOUND("레드본 쿤하운드"),
    LEONBERGER("레온베르거"),
    LAKELAND_TERRIER("레이크랜드 테리어"),
    RHODESIAN_RIDGEBACK("로디지안 리지백"),
    LOWCHEN("로첸"),
    ROTTWEILER("로트바일러"),
    MASTIFF("마스티프"),
    MANCHESTER_TERRIER("맨체스터 테리어"),
    MALTESE("말티즈"),
    MUNSTERLANDER("문스터랜더"),
    MINIATURE_BULL_TERRIER("미니어처 불 테리어"),
    MINIATURE_SCHNAUZER("미니어처 슈나우저"),
    MINIATURE_PINSCHER("미니어처 핀셔"),
    MALTIPOO("말티푸"),
    MIXED_BREED("믹스견"),
    BASENJI("바센지"),
    BASSET_HOUND("바셋 하운드"),
    BERGER_PICARD("버거 피카드"),
    BERNESE_MOUNTAIN_DOG("버니즈 마운틴 독"),
    BEDLINGTON_TERRIER("베들링턴 테리어"),
    VALLEY_DOG("발바리"),
    BELGIAN_MALINOIS("벨기에 말리노이즈"),
    BELGIAN_TERVUREN("벨기에 테뷰런"),
    BELGIAN_GRIFFON("벨지안 그리펀"),
    BELGIAN_SHEEPDOG("벨지언 쉽독"),
    BORDER_COLLIE("보더콜리"),
    BORDER_TERRIER("보더 테리어"),
    BORDEAUX_MASTIFF("보르도 마스티프"),
    BORZOI("보르조이"),
    BOSLONG("보스롱"),
    BOSTON_TERRIER("보스턴 테리어"),
    BOXER("복서"),
    BOLOGNESE("볼로니즈"),
    BOERBOEL("보어보엘"),
    BOUVIER_DES_FLANDRES("부비에 데 플랑드르"),
    BULLGAE("불개"),
    BULLDOG("불도그"),
    BULLY_KUTTA("불리 쿠타"),
    BULL_MASTIFF("불 마스티프"),
    BULL_TERRIER("불 테리어"),
    BROHOLMER("브로홀머"),
    BRUSSELS_GRIFFON("브뤼셀 그리폰"),
    BRIARD("브리어드"),
    BRITTANY("브리타니"),
    BLACK_RUSSIAN_TERRIER("블랙 러시안 테리어"),
    BLACK_AND_TAN_COONHOUND("블랙 앤드 탄 쿤하운드"),
    BLUETICK_COONHOUND("블루틱 쿤하운드"),
    BLOODHOUND("블러드 하운드"),
    BEAGLE("비글"),
    BICHON_FRISE("비숑 프리제"),
    BEARDED_COLLIE("비어디드 콜리"),
    VIZSLA("비즐라"),
    SAMOYED("사모예드"),
    SARPLANINAC("사플라니낙"),
    SALUKI("살루키"),
    SABSAL("삽살개"),
    SHAR_PEI("샤페이"),
    SUSSEX_SPANIEL("서식스 스패니얼"),
    SAINT_BERNARD("세인트 버나드"),
    SHETLAND_SHEEPDOG("셰틀랜드 쉽독"),
    SOFT_COATED_WHEATEN_TERRIER("소프트 코티드 휘튼 테리어"),
    XOLOITZCUINTLI("솔로이츠 쿠인틀레"),
    SMOOTH_FOX_TERRIER("스무드 폭스 테리어"),
    SWEDISH_VALLHUND("스웨디시 발훈트"),
    SKYE_TERRIER("스카이 테리어"),
    SCOTTISH_DEERHOUND("스코티시 디어하운드"),
    SCOTTISH_TERRIER("스코티시 테리어"),
    SCHIPPERKE("스키퍼키"),
    STAFFORDSHIRE_BULL_TERRIER("스태퍼드셔 불테리어"),
    STANDARD_SCHNAUZER("스탠더드 슈나우저"),
    SPANISH_GREYHOUND("스패니시 그레이 하운드"),
    SPANISH_MASTIFF("스패니시 마스티프"),
    SPINONE_ITALIANO("스피노네 이탈리아노"),
    SPITZ("스피츠"),
    SHIBA_INU("시바견"),
    SIBERIAN_HUSKY("시베리안 허스키"),
    SHIH_TZU("시추"),
    SHIKOKU("시코쿠견"),
    SEALYHAM_TERRIER("실리엄 테리어"),
    SILKY_TERRIER("실키 테리어"),
    ANATOLIAN_SHEPHERD_DOG("아나톨리아 셰퍼드"),
    AMERICAN_BULLDOG("아메리칸 불독"),
    AMERICAN_BULLY("아메리칸 불리"),
    AMERICAN_STAFFORDSHIRE_TERRIER("아메리칸 스태퍼드셔 테리어"),
    AMERICAN_AKITA("아메리칸 아키다"),
    AMERICAN_ESKIMO_DOG("아메리칸 에스키모 독"),
    AMERICAN_INDIAN_DOG("아메리칸 인디언 독"),
    AMERICAN_WATER_SPANIEL("아메리칸 워터 스패니얼"),
    AMERICAN_COCKER_SPANIEL("아메리칸 코커 스패니얼"),
    AMERICAN_FOXHOUND("아메리칸 폭스하운드"),
    AIDI("아이디"),
    IRISH_SOFT_COATED_WHEATEN_TERRIER("아이리시 소프트코티드 휘튼 테리어"),
    IRISH_RED_AND_WHITE_SETTER("아이리시 레드 앤드 화이트 세터"),
    IRISH_SETTER("아이리시 세터"),
    IRISH_WOLFHOUND("아이리시 울프 하운드"),
    IRISH_WATER_SPANIEL("아이리시 워터 스패니얼"),
    IRISH_TERRIER("아이리시 테리어"),
    AZAWAKH("아자와크"),
    AKITA("아키타"),
    AFFENPINSCHER("아펜핀셔"),
    AFGHAN_HOUND("아프간 하운드"),
    ALASKAN_MALAMUTE("알래스칸 맬러뮤트"),
    ALASKAN_KLEE_KAI("알래스칸 클리카이"),
    ESTRELA_MOUNTAIN_DOG("에스트렐라 마운틴 독"),
    AIREDALE_TERRIER("에어데일 테리어"),
    OVCARKA("오브차카"),
    AUSTRALIAN_SILKY_TERRIER("오스트레일리안 실키 테리어"),
    AUSTRALIAN_KELPIE("오스트레일리안 켈피"),
    AUSTRALIAN_SHEPHERD("오스트레일리안 셰퍼드"),
    AUSTRALIAN_CATTLE_DOG("오스트레일리안 캐틀 독"),
    AUSTRALIAN_TERRIER("오스트레일리안 테리어"),
    OTTERHOUND("오터 하운드"),
    OLD_ENGLISH_SHEEPDOG("올드 잉글리시 쉽독"),
    WEIMARANER("와이머라너"),
    WIRE_FOX_TERRIER("와이어 폭스 테리어"),
    WIREHAIRED_POINTING_GRIFFON("와이어헤어드 포인팅 그리펀"),
    YAKUTIAN_LAIKA("야쿠탄 라이카"),
    YORKSHIRE_TERRIER("요크셔 테리어"),
    EURASIER("유라시어"),
    WEST_HIGHLAND_WHITE_TERRIER("웨스트 하이랜드 화이트테리어"),
    WELSH_SPRINGER_SPANIEL("웰시 스프링어 스패니얼"),
    WELSH_CORGI("웰시 코기"),
    WELSH_TERRIER("웰시 테리어"),
    IBIZAN_HOUND("이비잔 하운드"),
    ITALIAN_GREYHOUND("이탈리안 그레이하운드"),
    ENGLISH_SETTER("잉글리시 세터"),
    ENGLISH_SPRINGER_SPANIEL("잉글리시 스프링어 스패니얼"),
    ENGLISH_COCKER_SPANIEL("잉글리시 코커 스패니얼"),
    ENGLISH_TOY_SPANIEL("잉글리시 토이 스패니얼"),
    ENGLISH_FOXHOUND("잉글리시 폭스하운드"),
    GIANT_SCHNAUZER("자이언트 슈나우저"),
    JAPANESE_CHIN("재패니즈 친"),
    JAPANESE_SPITZ("재패니즈 스피츠"),
    JACK_RUSSELL_TERRIER("잭 러셀 테리어"),
    GERMAN_SHEPHERD("저먼 셰퍼드"),
    GERMAN_SHORTHAIRED_POINTER("저먼 쇼트헤어드 포인터"),
    GERMAN_WIREHAIRED_POINTER("저먼 와이어헤어드 포인터"),
    GERMAN_PINSCHER("저먼 핀셔"),
    GERMAN_HUNTING_TERRIER("저먼 헌팅 테리어"),
    JEJU_DOG("제주개"),
    JINDO("진돗개"),
    CHOW_CHOW("차우차우"),
    CHINESE_SHAR_PEI("차이니즈 샤페이"),
    CHINESE_CRESTED("차이니즈 크레스티드"),
    CHESAPEAKE_BAY_RETRIEVER("체서피크 베이 레트리버"),
    CZECHOSLOVAKIAN_VLCIAK("체코슬로바키아 늑대개"),
    CHIHUAHUA("치와와"),
    CANE_CORSO("카네 코르소"),
    CARDIGAN_WELSH_CORGI("카디건 웰시 코기"),
    CAVALIER_KING_CHARLES_SPANIEL("카발리에 킹 찰스 스파니엘"),
    CATAHOULA_LEOPARD_DOG("카타훌라 레오파드 독"),
    KANGAL("캉갈"),
    CURLY_COATED_RETRIEVER("컬리코티드 레트리버"),
    KERRY_BLUE_TERRIER("케리 블루 테리어"),
    CAIRN_TERRIER("케언 테리어"),
    CANAAN_DOG("케이넌 독"),
    KEESHOND("케이스혼트"),
    KOREAN_MASTIFF("코리안 마스티프"),
    KOMONDOR("코몬도르"),
    COCKER_SPANIEL("코커 스패니얼"),
    COLLIE("콜리"),
    KUVASZ("쿠바스"),
    KOOIKERHONDJE("쿠이커혼제"),
    CLUMBER_SPANIEL("클럼버 스패니얼"),
    TOY_FOX_TERRIER("토이 폭스 테리어"),
    TIBETAN_MASTIFF("티베탄 마스티프"),
    TIBETAN_SPANIEL("티베탄 스패니얼"),
    TIBETAN_TERRIER("티베탄 테리어"),
    PHARAOH_HOUND("파라오 하운드"),
    PARSON_RUSSELL_TERRIER("파슨 러셀 테리어"),
    PAPILLON("파피용"),
    PATTERDALE_TERRIER("패터데일 테리어"),
    PUG("퍼그"),
    PEKINGESE("페키니즈"),
    PEMBROKE_WELSH_CORGI("펨브록 웰시 코기"),
    PORTUGUESE_WATER_DOG("포르투갈 워터 독"),
    POMERANIAN("포메라니안"),
    POINTER("포인터"),
    FOX_TERRIER("폭스 테리어"),
    POLISH_LOWLAND_SHEEPDOG("폴리시 롤런드 시프도그"),
    POMERANIAN_SPITZ("폼피츠"),
    POODLE("푸들"),
    PUMI("푸미"),
    PULI("풀리"),
    POONGSAN("풍산개"),
    FRENCH_BULLDOG("프렌치 불도그"),
    PETIT_BASSET_GRIFFON_VENDEEN("프티 바세 그리퐁 방댕"),
    FLAT_COATED_RETRIEVER("플랫코티드 레트리버"),
    PLOTT_HOUND("플롯 하운드"),
    FINNISH_SPITZ("피니시 스피츠"),
    PYRENEAN_MASTIFF("피레니언 마스티프"),
    PYRENEAN_SHEEPDOG("피레니언 쉽독"),
    PYRENEAN_SHEPHERD("피레니언 셰퍼드"),
    FIELD_SPANIEL("필드 스패니얼"),
    FILA_BRASILEIRO("필라 브라질레이로"),
    PIT_BULL_TERRIER("핏 불 테리어"),
    HARRIER("해리어"),
    HAVANESE("하바니즈"),
    HOKKAIDO_INU("홋카이도 이누"),
    WHITE_SWISS_SHEPHERD_DOG("화이트 스위스 셰퍼드 독"),
    WHIPPET("휘핏");

    private final String koreanName;

    Species(String koreanName) {
        this.koreanName = koreanName;
    }

    public String getKoreanName() {
        return koreanName;
    }
}

